# GitHub Action workflow file to be saved as .github/workflows/github-snake.yml in your profile repository

name: Generate Snake Animation

# Controls when the workflow will run
on:
  # Runs automatically every day
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day

  # Allows manual triggering of the workflow
  workflow_dispatch:

  # Runs on push to the main branch
  push:
    branches:
      - main

# Jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository content
      - uses: actions/checkout@v3

      # Generate the snake SVG
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: nazmisani
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Push the content of dist folder to output branch
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
